name: OpenGL

jobs:
  build:

    # Define machine where job will be executed
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Install GLUT
        run: sudo apt-get install freeglut3-dev mesa-utils libgtest-dev -y
      - name: Check GLUT
        run: dpkg -L freeglut3-dev
