name: Push_FastTest

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - Task_*    # Push events on branches whose name starts with Task_*

jobs:
  build:

    # Define machine where job will be executed
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - uses: actions/checkout@master
#      - uses: ./.github/actions/OpenGL
      - name: Install GLUT
        run: sudo apt-get update
#      -name: Clean
#        run: cmake --build . --target clean -- -j 4
#      - name: Download Google-Test
#        uses: CyberZHG/github-action-gtest@master
#      - name: Load CMake
#        run:  ls -l /usr/
#      - name: Load CMake2
#        run:  ls -l /usr/lib/
#      - name: Load CMake3
#        run:  ls -l /googletest
      #- name: Clean
      #  run: cmake --build . --target clean -- -j 4
      #- name: Build all
      #  run: cmake --build . --target DelaunayLib -- -j 4

