name: Push_FastTest

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - Task_*    # Push events on branches whose name starts with Task_*

jobs:
  build:

    # Define machine where job will be executed
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: List
        run: ls -l .github
      - name: Pwd
        run: ls -l .github/workflows
      - name: Pwd2
        run: ls -l .github/actions
      - name: Install Dependencies
        uses: ./.github/actions/OpenGL
#      - name: Install GLUT
#        run: sudo apt-get install freeglut3-dev mesa-utils libgtest-dev -y
      - name: Check GLUT
        run: dpkg -L freeglut3-dev
#      #- name: Download Google-Test
#      #  uses: CyberZHG/github-action-gtest@master
      - name: Load CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_RELEASE=TRUE -G "CodeBlocks - Unix Makefiles" .
      #- name: Clean
      #  run: cmake --build . --target clean -- -j 4
      #- name: Build all
      #  run: cmake --build . --target DelaunayLib -- -j 4

